import pytest
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException


@pytest.fixture
def driver(request):
    wd = webdriver.Chrome()
    #print(wd.capabilities)
    request.addfinalizer(wd.quit)
    return wd


def test_left_menu_validation(driver):
    driver.get("http://localhost/litecart/admin/")
    driver.find_element_by_name("username").send_keys("admin")
    driver.find_element_by_name("password").send_keys("admin")
    driver.find_element_by_name("login").click()
    is_element_present(driver, By.ID, 'box-apps-menu')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Appearence']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Template")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Logotype']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Logotype")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Catalog']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Catalog")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Product Groups']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Product Groups")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Option Groups']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Option Groups")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Manufacturers']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Manufacturers")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Suppliers']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Suppliers")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Delivery Statuses']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Delivery Statuses")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Sold Out Statuses']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Sold Out Statuses")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Quantity Units']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Quantity Units")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='CSV Import/Export']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"CSV Import/Export")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Countries']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Countries")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Currencies']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Currencies")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Customers']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Customers")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='CSV Import/Export']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"CSV Import/Export")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Newsletter']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Newsletter")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Geo Zones']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Geo Zones")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Languages']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Languages")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Storage Encoding']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Storage Encoding")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Modules']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Job Modules")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Customer']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Customer Modules")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Shipping']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Shipping Modules")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Payment']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Payment Modules")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Order Total']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Order Total Modules")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Order Success']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Order Success Modules")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Order Action']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Order Action Modules")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Orders']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Orders")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Order Statuses']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Order Statuses")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Pages']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Pages")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Reports']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Monthly Sales")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Most Sold Products']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Most Sold Products")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Most Shopping Customers']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Most Shopping Customers")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Settings']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Defaults']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='General']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Listings']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Images']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Checkout']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Advanced']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Security']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Settings")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Slides']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Slides")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Tax']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Tax Classes")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Tax Rates']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Tax Rates")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Translations']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Search Translations")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Scan Files']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Scan Files For Translations")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='CSV Import/Export']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"CSV Import/Export")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='Users']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"Users")]')
    driver.find_element_by_xpath("//ul[@id='box-apps-menu']//span[.='vQmods']").click()
    is_element_present(driver, By.XPATH, '//td[@id="content"]/h1[contains(.,"vQmods")]')


def is_element_present(driver, *args):
  try:
    wait = WebDriverWait(driver, 10)
    wait.until(EC.presence_of_element_located((args)))
    return True
  except NoSuchElementException:
    return False
